export const incidenceCodeList = [
  { id: 401, name: "Mantenimiento Programado / Preventivo" },
  { id: 402, name: "Mantenimiento Correctivo" },
  { id: 403, name: "Mantenimiento Taller Soldadura" },
  { id: 404, name: "Mantenimiento Llantas" },
  { id: 405, name: "Mantenimiento de Tolva / Loras" },
  { id: 406, name: "Equipo en taller" },
  { id: 407, name: "Equipo Inoperativo" },
  { id: 408, name: "Reparación Mecánica" },
  { id: 409, name: "Reperación Eléctrica" },
  { id: 410, name: "Cambio de Llantas" },
  { id: 411, name: "Reparación de Llantas" },
  { id: 412, name: "Traslado por Falla Mecánica - Eléctrica - Nemáticos" },
  { id: 413, name: "Traslado de llegada para atrnción Mecánica (Llegada del mecánico)" },
  { id: 414, name: "Tiempo de demora en ubicar al mecánico" },
  { id: 501, name: "Carguío de Bancos" },
  { id: 502, name: "Rotura de Muelle" },
  { id: 503, name: "Daño Tolva" },
  { id: 504, name: "Daño Llanta" },
  { id: 505, name: "Cuneteo del Equipo" },
  { id: 506, name: "Daño compuerta" },
  { id: 507, name: "Daño volquete" },
  { id: 601, name: "Falta de Operador" },
  { id: 602, name: "Bloqueo de Equipos" },
]